# Generated by Django 5.1.3 on 2024-11-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('video_data', models.TextField(blank=True, null=True)),
                ('image_data', models.TextField(blank=True, null=True))  # 새 필드 추가
            ],
        ),
    ]
